### ISSUE TITLE
csvimport repo missing

### ISSUE THREAD

**Issue by hotnuts21** [ui-libraries/plugin-Scripto#1]
The link to the forked CSVimport within the readme goes to a non existent repo.

Has the project been scrapped or is it just under a different name/user/repo?  

This appears to do a similar thing but doesnt mention the uni of Iowa or scripto compatibility such as needs review etc. https://github.com/Daniel-KM/CsvImport

**Comment by mbutler** [comment]
Updated link to Daniel-KM version.
