### ISSUE TITLE
Please submit pull request for  “getPageTranscriptionStatus” does not exist fix

### ISSUE THREAD

**Issue by ValeryCC** [ui-libraries/plugin-Scripto#2]
Thank you for fixing this bug in your latest version (2.3.2).

However, we had to upgrade to 2.4 due to a log in issue, where this is fixed. But 2.4 is missing your 2.3.2 fix. Can you submit a pull request to have your bug fix incorporated into the main Scripto project https://github.com/omeka/plugin-Scripto?

**Comment by mbutler** [comment]
I don't think they will accept the pull request since getPageTranscriptionStatus is custom to our fork of this plugin to work with the special theme. I will look into it, however.
