### ISSUE TITLE
500 server errors when saving transcriptions after upgrading MediaWiki to 1.37.1

### ISSUE THREAD

**Issue by ValeryCC** [ui-libraries/plugin-Scripto#3]
We've been getting 500 server errors when saving transcriptions after upgrading MediaWiki to 1.37.1.

This is a detailed Response error while trying to save a transcript:

    The "token" parameter must be set.
    Scripto_Service_Exception: The "token" parameter must be set. in /home/.../public_html/plugins/Scripto/libraries/Scripto/Service/MediaWiki.php:748
    Stack trace:
    #0 /home/.../public_html/plugins/Scripto/libraries/Scripto/Service/MediaWiki.php(556): Scripto_Service_MediaWiki->_request('edit', Array)
    #1 /home/.../public_html/plugins/Scripto/libraries/Scripto/Document.php(538): Scripto_Service_MediaWiki->edit('.MTE1MQ.MTQ2OA', 'PAINTINGS\nOWNED...', NULL)
    #2 /home/.../public_html/plugins/Scripto/controllers/IndexController.php(429): Scripto_Document->editTranscriptionPage('PAINTINGS\nOWNED...')
    #3 /home/.../public_html/application/libraries/Zend/Controller/Action.php(516): Scripto_IndexController->pageActionAction()
    #4 /home/.../public_html/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('pageActionActio...')
    #5 /home/.../public_html/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
    #6 /home/.../public_html/application/libraries/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
    #7 /home/.../public_html/application/libraries/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
    #8 /home/.../public_html/application/libraries/Omeka/Application.php(73): Zend_Application->run()
    #9 /home/.../public_html/index.php(23): Omeka_Application->run() #10 {main}

After the guidance of the forums, we wonder if this forked version includes some of the more recent Scripto updates that fixed the login and token errors. If not, could you merge in the changes from the updated Scripto plugin?

**Comment by mbutler** [comment]
The previously used "intoken" way to get tokens was deprecated since
MediaWiki 1.24 and was removed since 1.37. This change breaks any
Scripto installations that use versions less than 1.24 (released
2016-03-31).
